name: guidance-interval
channels:
  - pytorch
  - nvidia
dependencies:
  - python>=3.8, < 3.10
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
      - pyspng
      - diffusers==0.24.0
      - accelerate==0.25.0
      - huggingface_hub==0.24.7
